'use strict';

/**
 * Canonical error codes for the guild service. These codes follow the
 * `createError(code, message)` pattern shared with PVP/PVE cloud functions.
 */
const ERROR_CODES = Object.freeze({
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  UNKNOWN_ACTION: 'UNKNOWN_ACTION',
  RATE_LIMITED: 'RATE_LIMITED',
  ACTION_COOLDOWN: 'ACTION_COOLDOWN',
  ACTION_DAILY_LIMIT: 'ACTION_DAILY_LIMIT',
  INVALID_SIGNATURE: 'INVALID_SIGNATURE',
  INVALID_MEMBER: 'INVALID_MEMBER',
  INVALID_GUILD: 'INVALID_GUILD',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  NOT_IN_GUILD: 'NOT_IN_GUILD',
  BOSS_NOT_FOUND: 'BOSS_NOT_FOUND',
  BOSS_ATTEMPTS_EXHAUSTED: 'BOSS_ATTEMPTS_EXHAUSTED',
  BOSS_COOLDOWN: 'BOSS_COOLDOWN',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  INTERNAL_ERROR: 'GUILD_ACTION_FAILED',
  SECURITY_ALERT: 'GUILD_SECURITY_ALERT'
});

module.exports = {
  ERROR_CODES
};
